version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: ruby ./test.rb
workflows:
  CI:
    jobs:
      - test
